name: Build release Docker image and upload it to registry

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  DOCKER_IMAGE_NAME: evreg

jobs:
  build:
    runs-on: ubuntu-latest

    # Source: https://dev.to/onticdani/automatically-build-docker-images-with-github-actions-3n8e
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build Docker images
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:${{github.ref_name}}

      - name: Create a latest image as well
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:latest

      # Tag the Docker Images
      - name: Tag the image for the private registry $DOCKER_REGISTRY_URL
        run: docker tag $DOCKER_IMAGE_NAME:${{github.ref_name}} $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:${{github.ref_name}}

      - name: Create a latest image as well
        run: docker tag $DOCKER_IMAGE_NAME:${{github.ref_name}} $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest
