name: Build release Docker image

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: evreg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build Docker images
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:${{github.ref_name}}

      - name: Create a latest image as well
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:latest
